name: TVU BBS Build
run-name: ${{ github.actor }} is launching the build 🚀
on: [push]
jobs:
  Build:
    runs-on: self-hosted
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: Building...
        run: |
          go get .
          go build -v ./cmd/initbbs
          go build -v .
      - run: echo "🏁 The build completed successfully."
      - name: Copy binary to /usr/local/bin
        run: |
          cp initbbs /home/ghr/binaries
          cp tvubbs /home/ghr/binaries
      - run: echo "🏁 The copy completed successfully."
      - run: echo "🍏 This job's status is ${{ job.status }}."